import { notFound } from "next/navigation";
import { ArrowDown, CheckCircle2, Info } from "lucide-react";
import { demoProcesses } from "@/lib/process-intelligence";

export default async function ProcessDetail({ params }: { params: Promise<{ processId: string }> }) { const { processId }=await params; const process=demoProcesses.find(p=>p.id===processId); if(!process) notFound();
 return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{process.department} · Captured process</p><h1 className="mt-2 text-3xl font-semibold">{process.name}</h1><p className="mt-2 text-sm text-ink-muted">AI interpretations are labelled and kept separate from participant evidence.</p></div><div className="rounded-xl border border-blue/20 bg-blue-soft px-5 py-3"><span className="text-xs font-semibold uppercase">Opportunity score</span><strong className="ml-3 text-2xl">{process.score}</strong><details className="mt-2 text-xs"><summary className="cursor-pointer font-semibold">Why this score?</summary><p className="mt-1 max-w-xs">Frequency, annual effort, manual transfer and repetition increase the score. Sensitivity, judgement and complexity reduce it. Methodology: pi-score-v1.</p></details></div></header>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Frequency",process.frequency.replaceAll("_"," ")],["Duration",`${process.durationMinutes} min`],["People",process.peopleCount],["Annual effort",`≈ ${process.annualHours}h`],["Risk",process.risk]].map(([k,v])=><div className="surface-card p-4" key={k}><p className="text-xs text-ink-muted">{k}</p><strong className="mt-1 block capitalize">{v}</strong></div>)}</section>
 <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="surface-card p-5"><h2 className="text-lg font-semibold">Current state</h2><p className="text-xs text-ink-muted">AI-extracted flow · confidence varies by step</p><div className="mx-auto mt-5 max-w-xl">{process.steps.map((step,i)=><div key={step.title}><article className="rounded-xl border border-line bg-white p-4"><div className="flex justify-between gap-3"><strong>{step.title}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${step.classification==="HUMAN"?"bg-orange-100 text-orange-800":"bg-blue-soft text-blue"}`}>{step.classification.replaceAll("_"," ")}</span></div><p className="mt-2 text-xs text-ink-muted">{step.actor}{step.system?` · ${step.system}`:""}</p></article>{i<process.steps.length-1?<ArrowDown className="mx-auto my-2 h-4 w-4 text-ink-muted"/>:null}</div>)}</div></section>
 <div className="space-y-6"><section className="surface-card p-5"><h2 className="text-lg font-semibold">Pain and failure</h2><ul className="mt-3 space-y-2 text-sm">{process.painPoints.map(p=><li className="flex gap-2" key={p}><Info className="mt-0.5 h-4 w-4 flex-none text-coral"/>{p}</li>)}</ul><h3 className="mt-5 text-sm font-semibold">Systems</h3><div className="mt-2 flex flex-wrap gap-2">{process.systems.map(s=><span className="rounded-full border border-line px-3 py-1 text-xs" key={s}>{s}</span>)}</div></section><section className="surface-card p-5"><h2 className="text-lg font-semibold">Recommended intervention</h2><p className="mt-2 text-sm">Reduce manual preparation and transfers while retaining human approval.</p><div className="mt-4 flex gap-2"><button className="rounded-lg bg-navy px-3 py-2 text-sm font-semibold text-white"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Approve</button><button className="rounded-lg border border-line px-3 py-2 text-sm font-semibold">Needs research</button></div></section></div></div>
 <details className="surface-card p-5" open><summary className="cursor-pointer text-lg font-semibold">Source evidence</summary><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-ink-muted">Participant narrative</p><p className="mt-2 text-sm leading-6">{process.narrative}</p></div><div><p className="text-xs font-semibold uppercase text-ink-muted">Assumptions</p><p className="mt-2 text-sm">Annual effort uses participant-estimated frequency, duration and people. It is approximate, not measured impact.</p></div></div></details></div> }
