import Link from "next/link";
import { ArrowRight, Building2, CircleDot, Clock3, Lightbulb, Users } from "lucide-react";
import { MetricCard } from "@/components/process-intelligence/MetricCard";
import { demoProcesses } from "@/lib/process-intelligence";

export default function ProcessIntelligencePage() {
  const hours = demoProcesses.reduce((sum, process) => sum + process.annualHours, 0);
  const departments = new Set(demoProcesses.map((process) => process.department)).size;
  const opportunities = demoProcesses.filter((process) => process.score >= 60).length;
  return <div className="space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Process Intelligence</p><h1 className="mt-2 text-3xl font-semibold">How work really gets done</h1><p className="mt-2 max-w-2xl text-sm text-ink-muted">Capture work in people’s own words, understand recurring friction, and turn reviewed opportunities into measurable change.</p></div><Link className="rounded-lg bg-navy px-4 py-2.5 text-sm font-semibold text-white" href="/control/organisations/demo-mission-org/process-intelligence">Open organisation <ArrowRight className="ml-2 inline h-4 w-4" /></Link></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active campaigns" value="2" note="1 organisation in discovery"/><MetricCard label="Participation" value="38 / 52" note="31 have submitted"/><MetricCard label="Processes captured" value={demoProcesses.length} note={`${departments} departments represented`}/><MetricCard label="Annual effort represented" value={`${hours.toLocaleString()}h`} note="Participant estimates"/></section>
    <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="surface-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Discovery in progress</h2><p className="text-sm text-ink-muted">Organisation-wide AI Discovery</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">Active</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><Users className="h-4 w-4 text-blue"/><strong className="mt-2 block text-xl">31</strong><span className="text-xs text-ink-muted">contributors</span></div><div><CircleDot className="h-4 w-4 text-blue"/><strong className="mt-2 block text-xl">7</strong><span className="text-xs text-ink-muted">awaiting analysis</span></div><div><Lightbulb className="h-4 w-4 text-blue"/><strong className="mt-2 block text-xl">{opportunities}</strong><span className="text-xs text-ink-muted">high-potential</span></div></div><div className="mt-5 h-2 overflow-hidden rounded bg-line"><div className="h-full w-[73%] rounded bg-blue"/></div><p className="mt-2 text-xs text-ink-muted">73% of invited participants have contributed. Participation is shown for discovery coverage, never individual performance.</p></section>
    <section className="surface-card p-5"><h2 className="text-lg font-semibold">Transformation</h2><div className="mt-4 space-y-4"><div className="flex gap-3"><Building2 className="h-5 w-5 text-blue"/><div><strong className="block">3 initiatives active</strong><span className="text-xs text-ink-muted">1 designing · 1 pilot · 1 measuring</span></div></div><div className="flex gap-3"><Clock3 className="h-5 w-5 text-coral"/><div><strong className="block">486h potential recovery</strong><span className="text-xs text-ink-muted">Estimated, not realised</span></div></div></div></section></div>
  </div>;
}
