import { notFound } from "next/navigation";
import { resolveControlRequestContext } from "@/server/control-plane/context";
import { getControlRepository } from "@/server/control-plane";
import { requireControlCapability } from "@/lib/control-plane/permissions";
import { addProspectPersonAction } from "@/server/actions/control-prospects";
import { qualifyProspectAction,overrideQualificationAction } from "@/server/actions/control-sales";
const field = "rounded-md border border-line bg-surface px-3 py-2 text-sm";
export default async function ProspectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const ctx = await resolveControlRequestContext(); requireControlCapability(ctx.role, "prospect:view"); const repo = await getControlRepository(ctx);
  const [prospect, people, sources, facts,qualification] = await Promise.all([repo.prospects.get(ctx,id), repo.prospects.people(ctx,id), repo.prospects.sources(ctx,id), repo.prospects.facts(ctx,id),repo.sales.qualification(ctx,id)]); if (!prospect) notFound();
  return <div className="space-y-6"><div><p className="eyebrow">Prospect organisation</p><h1 className="mt-2 text-3xl font-semibold">{prospect.name}</h1><p className="mt-2 text-sm text-ink-muted">{prospect.website ?? "No website"} · {prospect.country ?? "Country unknown"} · {prospect.status}</p></div>
    <section className="surface-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Qualification</h2><p className="text-xs text-ink-muted">Deterministic decision support, not objective truth.</p></div><form action={qualifyProspectAction}><input type="hidden" name="prospectId" value={id}/><button className="rounded-md bg-navy px-4 py-2 text-sm font-semibold text-white">Run qualification</button></form></div>{qualification?<div className="mt-4"><div className="text-3xl font-semibold">{qualification.score}</div><div className="text-sm font-semibold">{qualification.effectiveCategory.replaceAll("_"," ")}</div><p className="mt-2 text-xs text-ink-muted">Computed: {qualification.computedCategory.replaceAll("_"," ")} · {qualification.methodologyVersion}</p><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Factor reasons</summary><ul className="mt-2 space-y-2">{(qualification.factors as {label:string;reason:string}[]).map(f=><li key={f.label} className="text-sm"><strong>{f.label}:</strong> {f.reason}</li>)}</ul></details><form action={overrideQualificationAction} className="mt-4 grid gap-2 sm:grid-cols-3"><input type="hidden" name="prospectId" value={id}/><select name="category" className={field}>{["strong_fit","potential_fit","review_required","poor_fit"].map(x=><option key={x}>{x}</option>)}</select><input required name="reason" placeholder="Override reason required" className={field}/><button className="rounded-md border border-line px-3 text-sm font-semibold">Apply override</button></form></div>:<p className="mt-5 text-sm text-ink-muted">Not assessed yet.</p>}</section>
    <div className="grid gap-5 xl:grid-cols-2"><section className="surface-card p-5"><h2 className="text-lg font-semibold">People</h2><ul className="mt-4 space-y-3">{people.map(p=><li key={p.id} className="border-b border-line pb-3"><div className="font-semibold">{p.name}</div><div className="text-sm text-ink-muted">{p.role ?? "Role unknown"} {p.email ? `· ${p.email}` : ""}</div><div className="text-xs text-ink-subtle">{p.verificationState.replaceAll("_"," ")}</div></li>)}</ul><form action={addProspectPersonAction} className="mt-4 grid gap-2"><input type="hidden" name="prospectId" value={id}/><input required name="name" placeholder="Name" className={field}/><input name="role" placeholder="Role" className={field}/><input name="email" type="email" placeholder="Work email" className={field}/><input name="sourceUrl" type="url" placeholder="Public source URL" className={field}/><button className="rounded-md bg-navy px-4 py-2 text-sm font-semibold text-white">Add person</button></form></section>
      <section className="surface-card p-5"><h2 className="text-lg font-semibold">Research facts</h2><p className="mt-1 text-xs text-ink-muted">Extracted facts remain unverified until reviewed.</p><ul className="mt-4 space-y-4">{facts.map(f=><li key={f.id}><div className="text-xs font-semibold uppercase text-ink-muted">{f.field}</div><div className="mt-1 text-sm">{f.value}</div><a href={f.sourceUrl} className="mt-1 block text-xs text-blue hover:underline">{f.authority} · {f.locator} · {f.verificationState.replaceAll("_"," ")}</a>{f.injectionSuspected && <div className="text-xs font-semibold text-critical">Injection-shaped content detected</div>}</li>)}</ul>{facts.length===0&&<p className="mt-5 text-sm text-ink-muted">No research facts saved yet.</p>}</section></div>
    <section className="surface-card p-5"><h2 className="text-lg font-semibold">Sources</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{sources.map(s=><a key={s.id} href={s.url} className="rounded-md border border-line p-3 text-sm hover:bg-surface-sunken"><div className="font-semibold">{s.title ?? s.url}</div><div className="text-xs text-ink-muted">{s.authority} · {s.extractionStatus}</div></a>)}</div></section>
  </div>;
}
