import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { nunitoSans, quicksand } from "@/app/fonts";
import { appConfig } from "@/lib/config";
import { ToastProvider } from "@/components/shared/Toast";

/**
 * `metadataBase` is the *marketing* origin, not the application one. Canonical
 * URLs, OpenGraph URLs and the sitemap all describe the public site, which in
 * production runs on a different host from the app. Both are configuration
 * (`NEXT_PUBLIC_MARKETING_URL` / `NEXT_PUBLIC_APP_URL`) so neither host is
 * written into a component.
 */
export const metadata: Metadata = {
  metadataBase: new URL(appConfig.marketingUrl),
  title: {
    default: "Pegasus Mission OS",
    template: "%s | Pegasus Mission OS",
  },
  description:
    "The operating system for mission-driven organisations. Connect funding, programmes, finances, relationships, evidence and reporting in one intelligent system.",
  applicationName: "Pegasus Mission OS",
  authors: [{ name: "Pegasus Information Studio", url: appConfig.studioUrl }],
  creator: "Pegasus Information Studio",
  publisher: "Pegasus Information Studio",
  category: "technology",
  keywords: [
    "charity management software",
    "nonprofit operating system",
    "grant management software",
    "impact reporting software",
    "programme management for charities",
    "funding intelligence",
    "Pegasus Mission OS",
  ],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  verification: { google: process.env.GOOGLE_SITE_VERIFICATION || undefined },
  formatDetection: { telephone: false },

  /*
   * Drawn from `src/app/icon.svg` and `apple-icon.svg`, which are the brand
   * mark on the fixed navy ground. SVG rather than .ico so the arc stays sharp
   * on a high-density display, with the navy plate keeping the coral legible
   * against both a light and a dark browser chrome.
   */
  icons: {
    icon: "/icon.svg",
    apple: "/apple-icon.svg",
  },
  manifest: "/manifest.webmanifest",

  /*
   * One share card for the whole site, generated by `scripts/build-og-image.mjs`.
   * Declared here rather than per route so no page can inherit a
   * `summary_large_image` card with nothing in it, which is what every route
   * did before this existed. Regenerate the PNG after any brand change.
   */
  openGraph: {
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "Pegasus Mission OS. Every mission deserves world-class technology.",
      },
    ],
  },
  twitter: {
    images: ["/og.png"],
  },
};

export const viewport: Viewport = {
  themeColor: "#fffcfa",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en-GB"
      className={`${nunitoSans.variable} ${quicksand.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        {/* Scroll-reveal content rests at opacity 0 until JS observes it. */}
        <noscript>
          <style>{`.reveal{opacity:1!important;transform:none!important}`}</style>
        </noscript>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
