create table customer_accounts(id uuid primary key default gen_random_uuid(),prospect_organisation_id uuid not null unique references prospect_organisations(id) on delete restrict,organisation_id uuid not null unique references organisations(id) on delete restrict,status text not null check(status in('provisioning','active','failed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table customer_conversions(id uuid primary key default gen_random_uuid(),prospect_organisation_id uuid not null unique references prospect_organisations(id) on delete restrict,customer_account_id uuid not null unique references customer_accounts(id) on delete restrict,idempotency_key text not null unique,converted_by uuid not null references internal_users(id),reason text not null check(length(trim(reason))>0),converted_at timestamptz not null default now());
create table provisioning_runs(id uuid primary key default gen_random_uuid(),customer_conversion_id uuid not null unique references customer_conversions(id) on delete restrict,state text not null check(state in('started','completed','failed')),idempotency_key text not null unique,failure_reason text,started_at timestamptz not null default now(),completed_at timestamptz,check(state<>'completed' or completed_at is not null));
create table customer_admin_invitations(id uuid primary key default gen_random_uuid(),customer_account_id uuid not null references customer_accounts(id) on delete cascade,email text not null,name text not null,status text not null default 'pending' check(status in('pending','sent','accepted','failed')),provider_reference text,created_at timestamptz not null default now(),unique(customer_account_id,email));
alter table customer_accounts enable row level security;alter table customer_conversions enable row level security;alter table provisioning_runs enable row level security;alter table customer_admin_invitations enable row level security;
grant select on customer_accounts,customer_conversions,provisioning_runs,customer_admin_invitations to authenticated;
create policy customer_accounts_select on customer_accounts for select using(is_active_internal_user());create policy customer_conversions_select on customer_conversions for select using(is_active_internal_user());create policy provisioning_runs_select on provisioning_runs for select using(is_active_internal_user());create policy customer_admin_invitations_select on customer_admin_invitations for select using(is_active_internal_user());
create or replace function provision_customer_from_prospect(target_prospect_id uuid,administrator_email text,administrator_name text,conversion_reason text,operation_key text,correlation_id text) returns jsonb language plpgsql security definer set search_path=public as $$
declare p prospect_organisations%rowtype;o sales_opportunities%rowtype;existing customer_conversions%rowtype;org_id uuid;account_id uuid;conversion_id uuid;run_id uuid;
begin
if not internal_has_role(array['super_admin','operations']::internal_role[]) then raise exception 'organisation:create capability required';end if;
if nullif(trim(conversion_reason),'') is null then raise exception 'reason required';end if;if nullif(trim(operation_key),'') is null then raise exception 'idempotency key required';end if;if administrator_email !~* '^[^@]+@[^@]+\.[^@]+$' then raise exception 'valid administrator email required';end if;
select * into existing from customer_conversions where prospect_organisation_id=target_prospect_id or idempotency_key=operation_key limit 1;if found then return jsonb_build_object('account_id',existing.customer_account_id,'conversion_id',existing.id,'existing',true);end if;
select * into strict p from prospect_organisations where id=target_prospect_id for update;select * into strict o from sales_opportunities where prospect_organisation_id=target_prospect_id for update;if o.stage<>'won' then raise exception 'only a won opportunity can be converted';end if;
insert into organisations(name,legal_name,type,website,is_demo,ai_enabled) values(p.name,p.name,coalesce(p.organisation_type,'other'),p.website,false,true) returning id into org_id;
insert into customer_accounts(prospect_organisation_id,organisation_id,status) values(p.id,org_id,'active') returning id into account_id;
insert into customer_conversions(prospect_organisation_id,customer_account_id,idempotency_key,converted_by,reason) values(p.id,account_id,operation_key,auth.uid(),conversion_reason) returning id into conversion_id;
insert into provisioning_runs(customer_conversion_id,state,idempotency_key,completed_at) values(conversion_id,'completed',operation_key,now()) returning id into run_id;
insert into customer_admin_invitations(customer_account_id,email,name) values(account_id,lower(trim(administrator_email)),trim(administrator_name));update prospect_organisations set status='converted',updated_at=now() where id=p.id;
insert into internal_audit_events(actor_id,action,target_type,target_id,organisation_id,reason,after_metadata,request_id) values(auth.uid(),'customer.provision','customer_conversion',conversion_id::text,org_id,conversion_reason,jsonb_build_object('prospect_id',p.id,'customer_account_id',account_id,'organisation_id',org_id,'provisioning_run_id',run_id),correlation_id);
return jsonb_build_object('account_id',account_id,'conversion_id',conversion_id,'run_id',run_id,'organisation_id',org_id,'existing',false);
end $$;
revoke all on function provision_customer_from_prospect(uuid,text,text,text,text,text) from public;grant execute on function provision_customer_from_prospect(uuid,text,text,text,text,text) to authenticated;
