-- Live Control projections for captured process evidence.
create or replace function control_list_process_submissions(p_organisation_id uuid)
returns table(id uuid,organisation_id uuid,process_name text,department text,team text,participant_name text,frequency text,duration_minutes integer,people_count integer,annual_hours numeric,systems text[],analysis_status process_analysis_status,submitted_at timestamptz,narrative text,friction_text text,human_judgement_text text,sensitive_data text[],magic_removal text)
language sql security definer set search_path=public stable as $$
 select s.id,s.organisation_id,s.process_name,p.department,p.team,nullif(trim(concat_ws(' ',p.first_name,p.last_name)),''),s.frequency,s.duration_minutes,s.people_count,s.annual_hours,s.systems,s.analysis_status,s.submitted_at,s.narrative,s.friction_text,s.human_judgement_text,s.sensitive_data,s.magic_removal
 from process_submissions s left join process_participants p on p.id=s.participant_id
 where is_active_internal_user() and s.organisation_id=p_organisation_id order by s.submitted_at desc
$$;
create or replace function control_process_intelligence_summary(p_organisation_id uuid) returns jsonb language sql security definer set search_path=public stable as $$
 select case when is_active_internal_user() then jsonb_build_object('organisation',jsonb_build_object('id',o.id,'name',o.name,'legalName',o.legal_name,'type',o.type),'campaigns',(select count(*) from process_intake_campaigns c where c.organisation_id=o.id),'activeCampaigns',(select count(*) from process_intake_campaigns c where c.organisation_id=o.id and c.status='active'),'participants',(select count(*) from process_participants p where p.organisation_id=o.id),'contributors',(select count(*) from process_participants p where p.organisation_id=o.id and p.processes_submitted>0),'processes',(select count(*) from process_submissions s where s.organisation_id=o.id),'annualHours',(select coalesce(sum(s.annual_hours),0) from process_submissions s where s.organisation_id=o.id),'departments',(select count(distinct p.department) from process_participants p where p.organisation_id=o.id and p.department is not null),'awaitingAnalysis',(select count(*) from process_submissions s where s.organisation_id=o.id and s.analysis_status in ('queued','processing')),'opportunities',(select count(*) from process_ai_opportunities a where a.organisation_id=o.id)) else null end from organisations o where o.id=p_organisation_id and o.archived_at is null
$$;
create or replace function control_get_process_submission(p_submission_id uuid) returns jsonb language sql security definer set search_path=public stable as $$
 select case when is_active_internal_user() then jsonb_build_object('id',s.id,'organisationId',s.organisation_id,'name',s.process_name,'department',p.department,'team',p.team,'participantName',nullif(trim(concat_ws(' ',p.first_name,p.last_name)),''),'frequency',s.frequency,'durationMinutes',s.duration_minutes,'peopleCount',s.people_count,'annualHours',s.annual_hours,'systems',s.systems,'analysisStatus',s.analysis_status,'submittedAt',s.submitted_at,'narrative',s.narrative,'friction',s.friction_text,'humanJudgement',s.human_judgement_text,'sensitiveData',s.sensitive_data,'magicRemoval',s.magic_removal,'effortAssumptions',s.effort_assumptions,'steps',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'order',x.step_order,'title',x.title,'description',x.description,'actor',x.actor,'system',x.system_name,'classification',x.classification,'reasoning',x.reasoning,'confidence',x.confidence) order by x.step_order) from process_steps x where x.submission_id=s.id),'[]'::jsonb),'opportunities',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'type',a.opportunity_type,'score',a.opportunity_score,'confidence',a.confidence,'benefit',a.expected_benefit,'components',a.score_components)) from process_ai_opportunities a where a.submission_id=s.id),'[]'::jsonb)) else null end from process_submissions s left join process_participants p on p.id=s.participant_id where s.id=p_submission_id
$$;
revoke all on function control_list_process_submissions(uuid),control_process_intelligence_summary(uuid),control_get_process_submission(uuid) from public;
grant execute on function control_list_process_submissions(uuid),control_process_intelligence_summary(uuid),control_get_process_submission(uuid) to authenticated;
