import{describe,expect,it}from"vitest";import{createControlRequestContext}from"@/server/control-plane/context";import{createInMemoryControlRepository,type ControlMemoryState}from"@/server/control-plane/in-memory";import{createInternalTask,movePipelineStage,overrideQualification,qualifyProspect}from"@/server/control-plane/sales-service";
const now="2026-08-19T10:00:00Z";const state=():ControlMemoryState=>({users:[],audit:[],prospects:[{id:"p1",name:"Green Futures",country:"United Kingdom",organisationType:"Charity",focusAreas:["Youth programmes"],sizeIndicators:["25 staff"],publicFinancialIndicators:["Grant funded income"],publicProgrammeIndicators:["Multiple projects and impact reports"],status:"researched",source:"manual",createdAt:now,updatedAt:now}],prospectPeople:[],prospectSources:[],prospectFacts:[],salesOpportunities:[],prospectQualifications:[],internalTasks:[],outreachTemplates:[],outreachSequences:[],sequenceSteps:[],sequenceEnrollments:[],contactCompliance:[],outreachSendRequests:[],customerAccounts:[],customerConversions:[],provisioningRuns:[],onboardingPlans:[],onboardingSteps:[],activationCriteria:[],customerValueEvents:[],activationSnapshots:[],customerMetadata:[],customerHealthSnapshots:[],supportSessions:[],supportAccessEvents:[],usageEvents:[],customerFeedback:[],featureFlags:[],featureTargets:[],aiTraces:[],systemStatuses:[]});const ctx=createControlRequestContext({internalUserId:"u1",role:"sales",requestId:"r1",now:()=>new Date(now)});
describe("CONTROL-3 services",()=>{
 it("stores computed qualification with reasons",async()=>{const data=state();const q=await qualifyProspect(ctx,createInMemoryControlRepository(data),"p1");expect(q.methodologyVersion).toBe("prospect-fit-v1");expect(q.factors).toHaveLength(11);expect(data.audit.at(-1)?.action).toBe("prospect.qualify");});
 it("requires an override reason and preserves computed category",async()=>{const data=state(),repo=createInMemoryControlRepository(data);const q=await qualifyProspect(ctx,repo,"p1");await expect(overrideQualification(ctx,repo,"p1","poor_fit"," ")).rejects.toThrow("reason");const changed=await overrideQualification(ctx,repo,"p1","poor_fit","Commercial timing");expect(changed.computedCategory).toBe(q.computedCategory);expect(changed.effectiveCategory).toBe("poor_fit");expect(changed.overrideReason).toBe("Commercial timing");});
 it("requires a lost reason",async()=>{const repo=createInMemoryControlRepository(state());await expect(movePipelineStage(ctx,repo,"p1","lost")).rejects.toThrow("lost reason");});
 it("moves a prospect through explicit stages",async()=>{const data=state(),repo=createInMemoryControlRepository(data);await movePipelineStage(ctx,repo,"p1","qualified",{nextAction:"Book demo"});const item=await movePipelineStage(ctx,repo,"p1","demo");expect(item.stage).toBe("demo");expect(item.nextAction).toBe("Book demo");});
 it("creates inert intelligence/manual tasks without external actions",async()=>{const data=state();const task=await createInternalTask(ctx,createInMemoryControlRepository(data),{title:"Follow up",priority:"high",relatedEntity:{type:"prospect",id:"p1"}});expect(task).not.toHaveProperty("execute");expect(task.status).toBe("open");});
});
