import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { extname, join, relative } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Guards on the characters customers actually see.
 *
 * The em dash is the house style's one absolute prohibition. It is the single
 * most recognisable tell of machine-written prose, and a product whose whole
 * argument is that it does not fake things cannot sound like it was faked. The
 * rule is worth more as an absolute than as a guideline with exceptions: a
 * rule with exceptions gets argued at every review, and a build failure gets
 * fixed.
 *
 * What counts as customer-facing: any string literal or JSX text node that
 * ships in `src/`. Code comments are exempt because nobody reads them from a
 * browser, and regular expressions are exempt because an em dash inside one is
 * matching somebody else's text rather than writing ours — the organisation
 * research parser splits third-party page titles on it, and must keep doing so.
 *
 * Replace one with what it was standing in for: a full stop where two
 * sentences got fused, a colon before a list or a label, a comma around an
 * aside, or brackets. Never leave the sentence unchanged with a comma dropped
 * in, which is how the tic survives a search-and-replace.
 */

const EM_DASH = "—";

/** Ranges of `source` that are comments or regex literals, blanked out. */
function stripNonCopy(source: string): string {
  const out = source.split("");
  let i = 0;
  const n = source.length;

  /** Whether a `/` at `pos` starts a regex rather than division. */
  const regexCanStart = (pos: number): boolean => {
    for (let j = pos - 1; j >= 0; j--) {
      const c = source[j]!;
      if (/\s/.test(c)) continue;
      return "(,=:[!&|?{};+-*%<>~^".includes(c);
    }
    return true;
  };

  const blank = (from: number, to: number) => {
    for (let j = from; j < to && j < n; j++) {
      if (out[j] !== "\n") out[j] = " ";
    }
  };

  while (i < n) {
    const c = source[i]!;

    if (c === "/" && source[i + 1] === "/") {
      const end = source.indexOf("\n", i);
      blank(i, end === -1 ? n : end);
      i = end === -1 ? n : end;
      continue;
    }

    if (c === "/" && source[i + 1] === "*") {
      const end = source.indexOf("*/", i + 2);
      blank(i, end === -1 ? n : end + 2);
      i = end === -1 ? n : end + 2;
      continue;
    }

    if (c === "/" && regexCanStart(i)) {
      let j = i + 1;
      let inClass = false;
      let closed = false;
      while (j < n) {
        const d = source[j]!;
        if (d === "\\") { j += 2; continue; }
        if (d === "\n") break;              // an unterminated regex is division
        if (d === "[") inClass = true;
        else if (d === "]") inClass = false;
        else if (d === "/" && !inClass) { closed = true; break; }
        j++;
      }
      if (closed) { blank(i, j + 1); i = j + 1; continue; }
      i++;
      continue;
    }

    // A quote: skip its contents so a `//` or `/` inside a string is not read
    // as a comment or a regex. The contents stay in `out` — they are copy.
    if (c === '"' || c === "'" || c === "`") {
      let j = i + 1;
      while (j < n) {
        const d = source[j]!;
        if (d === "\\") { j += 2; continue; }
        if (d === c) break;
        if (d === "\n" && c !== "`") break; // unterminated: an apostrophe in JSX
        j++;
      }
      i = j + 1;
      continue;
    }

    i++;
  }

  return out.join("");
}

function sourceFiles(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      found.push(...sourceFiles(path));
    } else if ([".ts", ".tsx"].includes(extname(path))) {
      found.push(path);
    }
  }
  return found;
}

describe("brand assets", () => {
  /**
   * A share card is invisible from inside the product: nothing renders it, no
   * page links to it, and the failure mode is a blank card on someone else's
   * timeline weeks later. `summary_large_image` was declared for months with
   * no image behind it, which is exactly that failure.
   *
   * The PNG is generated by `scripts/build-og-image.mjs`; this only checks it
   * is still there and still the size the meta tags promise.
   */
  it("ships every asset the metadata promises", () => {
    const root = process.cwd();

    for (const asset of ["public/og.png", "src/app/icon.svg", "src/app/apple-icon.svg"]) {
      expect(existsSync(join(root, asset)), `${asset} is missing`).toBe(true);
    }

    // PNG dimensions live in the IHDR chunk: 16 bytes in, two big-endian u32s.
    const png = readFileSync(join(root, "public/og.png"));
    expect(png.readUInt32BE(16), "og.png width").toBe(1200);
    expect(png.readUInt32BE(20), "og.png height").toBe(630);
  });
});

describe("customer-facing copy", () => {
  it("shows no em dash anywhere a customer can read one", () => {
    const root = process.cwd();
    const offenders: string[] = [];

    for (const path of sourceFiles(join(root, "src"))) {
      const source = readFileSync(path, "utf8");
      if (!source.includes(EM_DASH)) continue;

      stripNonCopy(source)
        .split("\n")
        .forEach((line, index) => {
          if (line.includes(EM_DASH)) {
            offenders.push(`${relative(root, path)}:${index + 1}  ${line.trim()}`);
          }
        });
    }

    expect(offenders, `em dash in customer-facing copy:\n${offenders.join("\n")}`)
      .toEqual([]);
  });
});
