import { describe,expect,it } from "vitest"; import { assessProspectFit } from "@/lib/control-plane/prospect-fit"; import type { ProspectOrganisation,ProspectFact } from "@/server/control-plane/types";
const prospect=(overrides:Partial<ProspectOrganisation>={}):ProspectOrganisation=>({id:"p1",name:"Green Futures",country:"United Kingdom",organisationType:"Charity",focusAreas:["Youth programmes"],sizeIndicators:["25 staff"],publicFinancialIndicators:["Grant funded income"],publicProgrammeIndicators:["Multiple projects and impact reports"],status:"researched",source:"manual",createdAt:"2026-01-01",updatedAt:"2026-01-01",...overrides});
const fact=(value:string):ProspectFact=>({id:crypto.randomUUID(),prospectOrganisationId:"p1",field:"overview",value,sourceId:crypto.randomUUID(),sourceUrl:"https://green.example/report",locator:"p.4",authority:"organisation",verificationState:"needs_review",confidence:.9,extractionMethod:"heading",injectionSuspected:false,extractedAt:"2026-01-01"});
describe("deterministic prospect fit",()=>{
 it("is deterministic and versioned",()=>{const input=[fact("Multiple funders, partners and reporting requirements")];expect(assessProspectFit(prospect(),input)).toEqual(assessProspectFit(prospect(),input));expect(assessProspectFit(prospect(),input).methodologyVersion).toBe("prospect-fit-v1");});
 it("returns explicit reasons, evidence and weights",()=>{const r=assessProspectFit(prospect(),[fact("Annual impact report and evaluation")]);expect(r.factors).toHaveLength(11);expect(r.factors.every(f=>f.reason&&f.weight>0)).toBe(true);expect(r.factors.find(f=>f.key==="evidence_maturity")?.evidenceUsed[0]).toContain("https://");});
 it("uses review_required when information is sparse",()=>{const r=assessProspectFit(prospect({country:undefined,organisationType:undefined,focusAreas:[],sizeIndicators:[],publicFinancialIndicators:[],publicProgrammeIndicators:[]}),[]);expect(r.category).toBe("review_required");expect(r.missingInformation.length).toBeGreaterThan(5);});
 it("never presents unknown factors as negative evidence",()=>{const r=assessProspectFit(prospect({sizeIndicators:[]}),[]);expect(r.factors.find(f=>f.key==="digital_fragmentation")).toMatchObject({status:"unknown",score:0});});
 it("does not call or depend on AI",()=>{expect(assessProspectFit.toString()).not.toMatch(/anthropic|openai|runAi|prompt/i);});
});
