import Link from "next/link";
import { resolveControlRequestContext } from "@/server/control-plane/context";
import { getControlRepository } from "@/server/control-plane";
import { movePipelineAction } from "@/server/actions/control-sales";
import type { SalesPipelineStage } from "@/server/control-plane/types";
const stages:SalesPipelineStage[]=["discovered","researched","qualified","contacted","engaged","demo","evaluating","proposal","won","lost","nurture"];
export default async function PipelinePage({searchParams}:{searchParams:Promise<{view?:string;stage?:string}>}){
 const query=await searchParams,ctx=await resolveControlRequestContext(),repo=await getControlRepository(ctx);const [all,prospects]=await Promise.all([repo.sales.opportunities(ctx),repo.prospects.list(ctx)]);const items=query.stage?all.filter(i=>i.stage===query.stage):all;const view=query.view==="kanban"?"kanban":"table";const name=(id:string)=>prospects.find(p=>p.id===id)?.name??"Unknown";
 return <div className="space-y-6"><div className="flex items-end justify-between"><div><p className="eyebrow">Grow</p><h1 className="mt-2 text-3xl font-semibold">Pipeline</h1></div><div className="flex gap-3 text-sm"><Link href="/control/pipeline?view=table">Table</Link><Link href="/control/pipeline?view=kanban">Kanban</Link></div></div><div className="flex flex-wrap gap-2"><Link className="rounded-full border px-3 py-1 text-xs" href={`/control/pipeline?view=${view}`}>All</Link>{stages.map(s=><Link key={s} className="rounded-full border px-3 py-1 text-xs" href={`/control/pipeline?view=${view}&stage=${s}`}>{s}</Link>)}</div>
 {view==="kanban"?<div className="grid gap-3 overflow-x-auto lg:grid-cols-4">{stages.map(stage=><section key={stage} className="surface-card min-h-32 p-3"><h2 className="text-xs font-bold uppercase text-ink-muted">{stage}</h2>{items.filter(i=>i.stage===stage).map(i=><div key={i.id} className="mt-3 rounded border bg-surface p-3"><div className="font-semibold">{name(i.prospectOrganisationId)}</div><div className="mt-1 text-xs text-ink-muted">{i.nextAction??"No next action"}</div></div>)}</section>)}</div>:<div className="surface-card overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="bg-surface-sunken"><th className="p-4">Prospect</th><th>Stage</th><th>Next action</th><th>Expected value</th><th>Close target</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="p-4 font-semibold">{name(item.prospectOrganisationId)}</td><td><form action={movePipelineAction} className="flex flex-wrap gap-2"><input type="hidden" name="prospectId" value={item.prospectOrganisationId}/><select name="stage" defaultValue={item.stage} className="rounded border p-1">{stages.map(s=><option key={s}>{s}</option>)}</select><input name="lostReason" aria-label={`Lost reason for ${name(item.prospectOrganisationId)}`} placeholder="Lost reason if applicable" className="rounded border p-1"/><button className="text-xs font-semibold">Move</button></form></td><td>{item.nextAction??"Not set"}</td><td>{item.expectedValue==null?"Not set":`£${item.expectedValue.toLocaleString()}`}</td><td>{item.closeTarget??"Not set"}</td></tr>)}</tbody></table></div>}</div>;
}
